// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role_info.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	UserId               int32           `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	AccountId            string          `protobuf:"bytes,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	Name                 string          `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Level                int32           `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`
	BaseData             *UserBaseData   `protobuf:"bytes,5,opt,name=BaseData,proto3" json:"BaseData,omitempty"`
	DetailData           *UserDetailData `protobuf:"bytes,6,opt,name=DetailData,proto3" json:"DetailData,omitempty"`
	CreateTime           int64           `protobuf:"varint,7,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3417cd360819c4, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *User) GetBaseData() *UserBaseData {
	if m != nil {
		return m.BaseData
	}
	return nil
}

func (m *User) GetDetailData() *UserDetailData {
	if m != nil {
		return m.DetailData
	}
	return nil
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type UserBaseData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBaseData) Reset()         { *m = UserBaseData{} }
func (m *UserBaseData) String() string { return proto.CompactTextString(m) }
func (*UserBaseData) ProtoMessage()    {}
func (*UserBaseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3417cd360819c4, []int{1}
}

func (m *UserBaseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBaseData.Unmarshal(m, b)
}
func (m *UserBaseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBaseData.Marshal(b, m, deterministic)
}
func (m *UserBaseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBaseData.Merge(m, src)
}
func (m *UserBaseData) XXX_Size() int {
	return xxx_messageInfo_UserBaseData.Size(m)
}
func (m *UserBaseData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBaseData.DiscardUnknown(m)
}

var xxx_messageInfo_UserBaseData proto.InternalMessageInfo

type UserDetailData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetailData) Reset()         { *m = UserDetailData{} }
func (m *UserDetailData) String() string { return proto.CompactTextString(m) }
func (*UserDetailData) ProtoMessage()    {}
func (*UserDetailData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3417cd360819c4, []int{2}
}

func (m *UserDetailData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetailData.Unmarshal(m, b)
}
func (m *UserDetailData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetailData.Marshal(b, m, deterministic)
}
func (m *UserDetailData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetailData.Merge(m, src)
}
func (m *UserDetailData) XXX_Size() int {
	return xxx_messageInfo_UserDetailData.Size(m)
}
func (m *UserDetailData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetailData.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetailData proto.InternalMessageInfo

func init() {
	proto.RegisterType((*User)(nil), "protos.User")
	proto.RegisterType((*UserBaseData)(nil), "protos.UserBaseData")
	proto.RegisterType((*UserDetailData)(nil), "protos.UserDetailData")
}

func init() { proto.RegisterFile("role_info.proto", fileDescriptor_ba3417cd360819c4) }

var fileDescriptor_ba3417cd360819c4 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xbf, 0x4a, 0xc6, 0x30,
	0x10, 0x27, 0x7e, 0x6d, 0xf5, 0x3b, 0xa5, 0xca, 0x51, 0x4a, 0x06, 0x91, 0xd0, 0x29, 0x53, 0x11,
	0x05, 0x77, 0xb5, 0x4b, 0x41, 0x1c, 0x82, 0xce, 0x12, 0xdb, 0x13, 0x0a, 0x6d, 0x23, 0x49, 0xf4,
	0xb9, 0x7d, 0x04, 0x69, 0xaa, 0x36, 0x4e, 0x97, 0xfb, 0xfd, 0x0d, 0x07, 0xa7, 0xd6, 0x8c, 0xf4,
	0x32, 0xcc, 0x6f, 0xa6, 0x7e, 0xb7, 0xc6, 0x1b, 0xcc, 0xc2, 0x70, 0xd5, 0x17, 0x83, 0xe4, 0xd9,
	0x91, 0xc5, 0x12, 0xb2, 0x65, 0xb6, 0x3d, 0x67, 0x82, 0xc9, 0x54, 0xfd, 0x6c, 0x78, 0x0e, 0xfb,
	0xdb, 0xae, 0x33, 0x1f, 0xb3, 0x6f, 0x7b, 0x7e, 0x20, 0x98, 0xdc, 0xab, 0x0d, 0x40, 0x84, 0xe4,
	0x51, 0x4f, 0xc4, 0x77, 0x81, 0x08, 0x6f, 0x2c, 0x20, 0x7d, 0xa0, 0x4f, 0x1a, 0x79, 0x12, 0x82,
	0xd6, 0x05, 0x2f, 0xe1, 0xe8, 0x4e, 0x3b, 0x6a, 0xb4, 0xd7, 0x3c, 0x15, 0x4c, 0x1e, 0x5f, 0x15,
	0xeb, 0x57, 0x5c, 0xbd, 0x34, 0xfd, 0x72, 0xea, 0x4f, 0x85, 0x37, 0x00, 0x0d, 0x79, 0x3d, 0x8c,
	0xc1, 0x93, 0x05, 0x4f, 0x19, 0x7b, 0x36, 0x56, 0x45, 0x4a, 0xbc, 0x00, 0xb8, 0xb7, 0xa4, 0x3d,
	0x3d, 0x0d, 0x13, 0xf1, 0x43, 0xc1, 0xe4, 0x4e, 0x45, 0x48, 0x95, 0xc3, 0x49, 0xdc, 0x58, 0x9d,
	0x41, 0xfe, 0x3f, 0xed, 0x75, 0x3d, 0xce, 0xf5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0xbb,
	0x26, 0xa6, 0x36, 0x01, 0x00, 0x00,
}
