// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package node

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerState int32

const (
	ServerState_SS_CRASH   ServerState = 0
	ServerState_SS_NORMAL  ServerState = 1
	ServerState_SS_BUSY    ServerState = 2
	ServerState_SS_FIRE    ServerState = 3
	ServerState_SS_MAINTEN ServerState = 4
)

var ServerState_name = map[int32]string{
	0: "SS_CRASH",
	1: "SS_NORMAL",
	2: "SS_BUSY",
	3: "SS_FIRE",
	4: "SS_MAINTEN",
}

var ServerState_value = map[string]int32{
	"SS_CRASH":   0,
	"SS_NORMAL":  1,
	"SS_BUSY":    2,
	"SS_FIRE":    3,
	"SS_MAINTEN": 4,
}

func (x ServerState) String() string {
	return proto.EnumName(ServerState_name, int32(x))
}

func (ServerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

type ServerNodeMsgID int32

const (
	ServerNodeMsgID_SERVER_NODE_MSG_ID                  ServerNodeMsgID = 0
	ServerNodeMsgID_GATE_ROUTE_TO_LOGIN                 ServerNodeMsgID = 10001
	ServerNodeMsgID_LOGIN_ROUTE_TO_GATE                 ServerNodeMsgID = 10002
	ServerNodeMsgID_GATE_ROUTE_TO_GAME                  ServerNodeMsgID = 10003
	ServerNodeMsgID_GAME_ROUTE_TO_GATE                  ServerNodeMsgID = 10004
	ServerNodeMsgID_GATE_ROUTE_TO_CHAT                  ServerNodeMsgID = 10005
	ServerNodeMsgID_CHAT_ROUTE_TO_GATE                  ServerNodeMsgID = 10006
	ServerNodeMsgID_WORLD_ROUTE_TO_GATE                 ServerNodeMsgID = 10007
	ServerNodeMsgID_GATE_ROUTE_TO_WORLD                 ServerNodeMsgID = 10008
	ServerNodeMsgID_GAME_ROUTE_TO_CHAT                  ServerNodeMsgID = 10009
	ServerNodeMsgID_CHAT_ROUTE_TO_GAME                  ServerNodeMsgID = 10010
	ServerNodeMsgID_GAME_ROUTE_TO_WORLD                 ServerNodeMsgID = 10011
	ServerNodeMsgID_WORLD_ROUTE_TO_GAME                 ServerNodeMsgID = 10012
	ServerNodeMsgID_LOGIN_ROUTE_TO_WORLD                ServerNodeMsgID = 10013
	ServerNodeMsgID_WORLD_ROUTE_TO_LOGIN                ServerNodeMsgID = 10014
	ServerNodeMsgID_WORLD_ROUTE_TO_DB                   ServerNodeMsgID = 10015
	ServerNodeMsgID_DB_ROUTE_TO_WORLD                   ServerNodeMsgID = 10016
	ServerNodeMsgID_PLAYER_ROUTE_TO_GATE                ServerNodeMsgID = 10017
	ServerNodeMsgID_GATE_ROUTE_TO_PLAYER                ServerNodeMsgID = 10018
	ServerNodeMsgID_GAME_PLAYER_OFFLINE                 ServerNodeMsgID = 10051
	ServerNodeMsgID_REPORT_CLIENT_INFO_TO_SERVER        ServerNodeMsgID = 10054
	ServerNodeMsgID_MASTER_REPORT_SERVER_INFO_TO_SERVER ServerNodeMsgID = 10053
)

var ServerNodeMsgID_name = map[int32]string{
	0:     "SERVER_NODE_MSG_ID",
	10001: "GATE_ROUTE_TO_LOGIN",
	10002: "LOGIN_ROUTE_TO_GATE",
	10003: "GATE_ROUTE_TO_GAME",
	10004: "GAME_ROUTE_TO_GATE",
	10005: "GATE_ROUTE_TO_CHAT",
	10006: "CHAT_ROUTE_TO_GATE",
	10007: "WORLD_ROUTE_TO_GATE",
	10008: "GATE_ROUTE_TO_WORLD",
	10009: "GAME_ROUTE_TO_CHAT",
	10010: "CHAT_ROUTE_TO_GAME",
	10011: "GAME_ROUTE_TO_WORLD",
	10012: "WORLD_ROUTE_TO_GAME",
	10013: "LOGIN_ROUTE_TO_WORLD",
	10014: "WORLD_ROUTE_TO_LOGIN",
	10015: "WORLD_ROUTE_TO_DB",
	10016: "DB_ROUTE_TO_WORLD",
	10017: "PLAYER_ROUTE_TO_GATE",
	10018: "GATE_ROUTE_TO_PLAYER",
	10051: "GAME_PLAYER_OFFLINE",
	10054: "REPORT_CLIENT_INFO_TO_SERVER",
	10053: "MASTER_REPORT_SERVER_INFO_TO_SERVER",
}

var ServerNodeMsgID_value = map[string]int32{
	"SERVER_NODE_MSG_ID":                  0,
	"GATE_ROUTE_TO_LOGIN":                 10001,
	"LOGIN_ROUTE_TO_GATE":                 10002,
	"GATE_ROUTE_TO_GAME":                  10003,
	"GAME_ROUTE_TO_GATE":                  10004,
	"GATE_ROUTE_TO_CHAT":                  10005,
	"CHAT_ROUTE_TO_GATE":                  10006,
	"WORLD_ROUTE_TO_GATE":                 10007,
	"GATE_ROUTE_TO_WORLD":                 10008,
	"GAME_ROUTE_TO_CHAT":                  10009,
	"CHAT_ROUTE_TO_GAME":                  10010,
	"GAME_ROUTE_TO_WORLD":                 10011,
	"WORLD_ROUTE_TO_GAME":                 10012,
	"LOGIN_ROUTE_TO_WORLD":                10013,
	"WORLD_ROUTE_TO_LOGIN":                10014,
	"WORLD_ROUTE_TO_DB":                   10015,
	"DB_ROUTE_TO_WORLD":                   10016,
	"PLAYER_ROUTE_TO_GATE":                10017,
	"GATE_ROUTE_TO_PLAYER":                10018,
	"GAME_PLAYER_OFFLINE":                 10051,
	"REPORT_CLIENT_INFO_TO_SERVER":        10054,
	"MASTER_REPORT_SERVER_INFO_TO_SERVER": 10053,
}

func (x ServerNodeMsgID) String() string {
	return proto.EnumName(ServerNodeMsgID_name, int32(x))
}

func (ServerNodeMsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

type ServerReport struct {
	ServerId             int32       `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName           []byte      `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerIp             []byte      `protobuf:"bytes,3,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	ServerPort           int32       `protobuf:"varint,4,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	MaxOnline            int32       `protobuf:"varint,5,opt,name=max_online,json=maxOnline,proto3" json:"max_online,omitempty"`
	CurOnline            int32       `protobuf:"varint,6,opt,name=cur_online,json=curOnline,proto3" json:"cur_online,omitempty"`
	ServerState          ServerState `protobuf:"varint,7,opt,name=server_state,json=serverState,proto3,enum=ServerState" json:"server_state,omitempty"`
	ServerType           int32       `protobuf:"varint,8,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerReport) Reset()         { *m = ServerReport{} }
func (m *ServerReport) String() string { return proto.CompactTextString(m) }
func (*ServerReport) ProtoMessage()    {}
func (*ServerReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *ServerReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerReport.Unmarshal(m, b)
}
func (m *ServerReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerReport.Marshal(b, m, deterministic)
}
func (m *ServerReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerReport.Merge(m, src)
}
func (m *ServerReport) XXX_Size() int {
	return xxx_messageInfo_ServerReport.Size(m)
}
func (m *ServerReport) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerReport.DiscardUnknown(m)
}

var xxx_messageInfo_ServerReport proto.InternalMessageInfo

func (m *ServerReport) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *ServerReport) GetServerName() []byte {
	if m != nil {
		return m.ServerName
	}
	return nil
}

func (m *ServerReport) GetServerIp() []byte {
	if m != nil {
		return m.ServerIp
	}
	return nil
}

func (m *ServerReport) GetServerPort() int32 {
	if m != nil {
		return m.ServerPort
	}
	return 0
}

func (m *ServerReport) GetMaxOnline() int32 {
	if m != nil {
		return m.MaxOnline
	}
	return 0
}

func (m *ServerReport) GetCurOnline() int32 {
	if m != nil {
		return m.CurOnline
	}
	return 0
}

func (m *ServerReport) GetServerState() ServerState {
	if m != nil {
		return m.ServerState
	}
	return ServerState_SS_CRASH
}

func (m *ServerReport) GetServerType() int32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

type ServerReportList struct {
	ServerInfo           []*ServerReport `protobuf:"bytes,1,rep,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ServerReportList) Reset()         { *m = ServerReportList{} }
func (m *ServerReportList) String() string { return proto.CompactTextString(m) }
func (*ServerReportList) ProtoMessage()    {}
func (*ServerReportList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *ServerReportList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerReportList.Unmarshal(m, b)
}
func (m *ServerReportList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerReportList.Marshal(b, m, deterministic)
}
func (m *ServerReportList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerReportList.Merge(m, src)
}
func (m *ServerReportList) XXX_Size() int {
	return xxx_messageInfo_ServerReportList.Size(m)
}
func (m *ServerReportList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerReportList.DiscardUnknown(m)
}

var xxx_messageInfo_ServerReportList proto.InternalMessageInfo

func (m *ServerReportList) GetServerInfo() []*ServerReport {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

type ServerHeartBeat struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerHeartBeat) Reset()         { *m = ServerHeartBeat{} }
func (m *ServerHeartBeat) String() string { return proto.CompactTextString(m) }
func (*ServerHeartBeat) ProtoMessage()    {}
func (*ServerHeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *ServerHeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerHeartBeat.Unmarshal(m, b)
}
func (m *ServerHeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerHeartBeat.Marshal(b, m, deterministic)
}
func (m *ServerHeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerHeartBeat.Merge(m, src)
}
func (m *ServerHeartBeat) XXX_Size() int {
	return xxx_messageInfo_ServerHeartBeat.Size(m)
}
func (m *ServerHeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerHeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_ServerHeartBeat proto.InternalMessageInfo

func (m *ServerHeartBeat) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type NodeToMasterPacket struct {
	ServerInfo           *ServerReport `protobuf:"bytes,1,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NodeToMasterPacket) Reset()         { *m = NodeToMasterPacket{} }
func (m *NodeToMasterPacket) String() string { return proto.CompactTextString(m) }
func (*NodeToMasterPacket) ProtoMessage()    {}
func (*NodeToMasterPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}

func (m *NodeToMasterPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeToMasterPacket.Unmarshal(m, b)
}
func (m *NodeToMasterPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeToMasterPacket.Marshal(b, m, deterministic)
}
func (m *NodeToMasterPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeToMasterPacket.Merge(m, src)
}
func (m *NodeToMasterPacket) XXX_Size() int {
	return xxx_messageInfo_NodeToMasterPacket.Size(m)
}
func (m *NodeToMasterPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeToMasterPacket.DiscardUnknown(m)
}

var xxx_messageInfo_NodeToMasterPacket proto.InternalMessageInfo

func (m *NodeToMasterPacket) GetServerInfo() *ServerReport {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

type MasterToNodePacket struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterToNodePacket) Reset()         { *m = MasterToNodePacket{} }
func (m *MasterToNodePacket) String() string { return proto.CompactTextString(m) }
func (*MasterToNodePacket) ProtoMessage()    {}
func (*MasterToNodePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{4}
}

func (m *MasterToNodePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterToNodePacket.Unmarshal(m, b)
}
func (m *MasterToNodePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterToNodePacket.Marshal(b, m, deterministic)
}
func (m *MasterToNodePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterToNodePacket.Merge(m, src)
}
func (m *MasterToNodePacket) XXX_Size() int {
	return xxx_messageInfo_MasterToNodePacket.Size(m)
}
func (m *MasterToNodePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterToNodePacket.DiscardUnknown(m)
}

var xxx_messageInfo_MasterToNodePacket proto.InternalMessageInfo

func (m *MasterToNodePacket) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type GateToLoginPacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GateToLoginPacket) Reset()         { *m = GateToLoginPacket{} }
func (m *GateToLoginPacket) String() string { return proto.CompactTextString(m) }
func (*GateToLoginPacket) ProtoMessage()    {}
func (*GateToLoginPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{5}
}

func (m *GateToLoginPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateToLoginPacket.Unmarshal(m, b)
}
func (m *GateToLoginPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateToLoginPacket.Marshal(b, m, deterministic)
}
func (m *GateToLoginPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateToLoginPacket.Merge(m, src)
}
func (m *GateToLoginPacket) XXX_Size() int {
	return xxx_messageInfo_GateToLoginPacket.Size(m)
}
func (m *GateToLoginPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GateToLoginPacket.DiscardUnknown(m)
}

var xxx_messageInfo_GateToLoginPacket proto.InternalMessageInfo

func (m *GateToLoginPacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GateToLoginPacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *GateToLoginPacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type LoginToGatePacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginToGatePacket) Reset()         { *m = LoginToGatePacket{} }
func (m *LoginToGatePacket) String() string { return proto.CompactTextString(m) }
func (*LoginToGatePacket) ProtoMessage()    {}
func (*LoginToGatePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{6}
}

func (m *LoginToGatePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginToGatePacket.Unmarshal(m, b)
}
func (m *LoginToGatePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginToGatePacket.Marshal(b, m, deterministic)
}
func (m *LoginToGatePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginToGatePacket.Merge(m, src)
}
func (m *LoginToGatePacket) XXX_Size() int {
	return xxx_messageInfo_LoginToGatePacket.Size(m)
}
func (m *LoginToGatePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginToGatePacket.DiscardUnknown(m)
}

var xxx_messageInfo_LoginToGatePacket proto.InternalMessageInfo

func (m *LoginToGatePacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *LoginToGatePacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *LoginToGatePacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type GateToGamePacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GateToGamePacket) Reset()         { *m = GateToGamePacket{} }
func (m *GateToGamePacket) String() string { return proto.CompactTextString(m) }
func (*GateToGamePacket) ProtoMessage()    {}
func (*GateToGamePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{7}
}

func (m *GateToGamePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateToGamePacket.Unmarshal(m, b)
}
func (m *GateToGamePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateToGamePacket.Marshal(b, m, deterministic)
}
func (m *GateToGamePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateToGamePacket.Merge(m, src)
}
func (m *GateToGamePacket) XXX_Size() int {
	return xxx_messageInfo_GateToGamePacket.Size(m)
}
func (m *GateToGamePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GateToGamePacket.DiscardUnknown(m)
}

var xxx_messageInfo_GateToGamePacket proto.InternalMessageInfo

func (m *GateToGamePacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GateToGamePacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *GateToGamePacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type GameToGatePacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameToGatePacket) Reset()         { *m = GameToGatePacket{} }
func (m *GameToGatePacket) String() string { return proto.CompactTextString(m) }
func (*GameToGatePacket) ProtoMessage()    {}
func (*GameToGatePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{8}
}

func (m *GameToGatePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameToGatePacket.Unmarshal(m, b)
}
func (m *GameToGatePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameToGatePacket.Marshal(b, m, deterministic)
}
func (m *GameToGatePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameToGatePacket.Merge(m, src)
}
func (m *GameToGatePacket) XXX_Size() int {
	return xxx_messageInfo_GameToGatePacket.Size(m)
}
func (m *GameToGatePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GameToGatePacket.DiscardUnknown(m)
}

var xxx_messageInfo_GameToGatePacket proto.InternalMessageInfo

func (m *GameToGatePacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GameToGatePacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *GameToGatePacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type GateToChatPacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GateToChatPacket) Reset()         { *m = GateToChatPacket{} }
func (m *GateToChatPacket) String() string { return proto.CompactTextString(m) }
func (*GateToChatPacket) ProtoMessage()    {}
func (*GateToChatPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{9}
}

func (m *GateToChatPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateToChatPacket.Unmarshal(m, b)
}
func (m *GateToChatPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateToChatPacket.Marshal(b, m, deterministic)
}
func (m *GateToChatPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateToChatPacket.Merge(m, src)
}
func (m *GateToChatPacket) XXX_Size() int {
	return xxx_messageInfo_GateToChatPacket.Size(m)
}
func (m *GateToChatPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GateToChatPacket.DiscardUnknown(m)
}

var xxx_messageInfo_GateToChatPacket proto.InternalMessageInfo

func (m *GateToChatPacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GateToChatPacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *GateToChatPacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type ChatToGatePacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatToGatePacket) Reset()         { *m = ChatToGatePacket{} }
func (m *ChatToGatePacket) String() string { return proto.CompactTextString(m) }
func (*ChatToGatePacket) ProtoMessage()    {}
func (*ChatToGatePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{10}
}

func (m *ChatToGatePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatToGatePacket.Unmarshal(m, b)
}
func (m *ChatToGatePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatToGatePacket.Marshal(b, m, deterministic)
}
func (m *ChatToGatePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatToGatePacket.Merge(m, src)
}
func (m *ChatToGatePacket) XXX_Size() int {
	return xxx_messageInfo_ChatToGatePacket.Size(m)
}
func (m *ChatToGatePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatToGatePacket.DiscardUnknown(m)
}

var xxx_messageInfo_ChatToGatePacket proto.InternalMessageInfo

func (m *ChatToGatePacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *ChatToGatePacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *ChatToGatePacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type WorldToGatePacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldToGatePacket) Reset()         { *m = WorldToGatePacket{} }
func (m *WorldToGatePacket) String() string { return proto.CompactTextString(m) }
func (*WorldToGatePacket) ProtoMessage()    {}
func (*WorldToGatePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{11}
}

func (m *WorldToGatePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldToGatePacket.Unmarshal(m, b)
}
func (m *WorldToGatePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldToGatePacket.Marshal(b, m, deterministic)
}
func (m *WorldToGatePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldToGatePacket.Merge(m, src)
}
func (m *WorldToGatePacket) XXX_Size() int {
	return xxx_messageInfo_WorldToGatePacket.Size(m)
}
func (m *WorldToGatePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldToGatePacket.DiscardUnknown(m)
}

var xxx_messageInfo_WorldToGatePacket proto.InternalMessageInfo

func (m *WorldToGatePacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *WorldToGatePacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *WorldToGatePacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type GateToWorldPacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GateToWorldPacket) Reset()         { *m = GateToWorldPacket{} }
func (m *GateToWorldPacket) String() string { return proto.CompactTextString(m) }
func (*GateToWorldPacket) ProtoMessage()    {}
func (*GateToWorldPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{12}
}

func (m *GateToWorldPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateToWorldPacket.Unmarshal(m, b)
}
func (m *GateToWorldPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateToWorldPacket.Marshal(b, m, deterministic)
}
func (m *GateToWorldPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateToWorldPacket.Merge(m, src)
}
func (m *GateToWorldPacket) XXX_Size() int {
	return xxx_messageInfo_GateToWorldPacket.Size(m)
}
func (m *GateToWorldPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GateToWorldPacket.DiscardUnknown(m)
}

var xxx_messageInfo_GateToWorldPacket proto.InternalMessageInfo

func (m *GateToWorldPacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GateToWorldPacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *GateToWorldPacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type GameToChatPacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameToChatPacket) Reset()         { *m = GameToChatPacket{} }
func (m *GameToChatPacket) String() string { return proto.CompactTextString(m) }
func (*GameToChatPacket) ProtoMessage()    {}
func (*GameToChatPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{13}
}

func (m *GameToChatPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameToChatPacket.Unmarshal(m, b)
}
func (m *GameToChatPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameToChatPacket.Marshal(b, m, deterministic)
}
func (m *GameToChatPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameToChatPacket.Merge(m, src)
}
func (m *GameToChatPacket) XXX_Size() int {
	return xxx_messageInfo_GameToChatPacket.Size(m)
}
func (m *GameToChatPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GameToChatPacket.DiscardUnknown(m)
}

var xxx_messageInfo_GameToChatPacket proto.InternalMessageInfo

func (m *GameToChatPacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GameToChatPacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *GameToChatPacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type ChatToGamePacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatToGamePacket) Reset()         { *m = ChatToGamePacket{} }
func (m *ChatToGamePacket) String() string { return proto.CompactTextString(m) }
func (*ChatToGamePacket) ProtoMessage()    {}
func (*ChatToGamePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{14}
}

func (m *ChatToGamePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatToGamePacket.Unmarshal(m, b)
}
func (m *ChatToGamePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatToGamePacket.Marshal(b, m, deterministic)
}
func (m *ChatToGamePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatToGamePacket.Merge(m, src)
}
func (m *ChatToGamePacket) XXX_Size() int {
	return xxx_messageInfo_ChatToGamePacket.Size(m)
}
func (m *ChatToGamePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatToGamePacket.DiscardUnknown(m)
}

var xxx_messageInfo_ChatToGamePacket proto.InternalMessageInfo

func (m *ChatToGamePacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *ChatToGamePacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *ChatToGamePacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type GameToWorldPacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameToWorldPacket) Reset()         { *m = GameToWorldPacket{} }
func (m *GameToWorldPacket) String() string { return proto.CompactTextString(m) }
func (*GameToWorldPacket) ProtoMessage()    {}
func (*GameToWorldPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{15}
}

func (m *GameToWorldPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameToWorldPacket.Unmarshal(m, b)
}
func (m *GameToWorldPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameToWorldPacket.Marshal(b, m, deterministic)
}
func (m *GameToWorldPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameToWorldPacket.Merge(m, src)
}
func (m *GameToWorldPacket) XXX_Size() int {
	return xxx_messageInfo_GameToWorldPacket.Size(m)
}
func (m *GameToWorldPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GameToWorldPacket.DiscardUnknown(m)
}

var xxx_messageInfo_GameToWorldPacket proto.InternalMessageInfo

func (m *GameToWorldPacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GameToWorldPacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *GameToWorldPacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type WorldToGamePacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldToGamePacket) Reset()         { *m = WorldToGamePacket{} }
func (m *WorldToGamePacket) String() string { return proto.CompactTextString(m) }
func (*WorldToGamePacket) ProtoMessage()    {}
func (*WorldToGamePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{16}
}

func (m *WorldToGamePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldToGamePacket.Unmarshal(m, b)
}
func (m *WorldToGamePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldToGamePacket.Marshal(b, m, deterministic)
}
func (m *WorldToGamePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldToGamePacket.Merge(m, src)
}
func (m *WorldToGamePacket) XXX_Size() int {
	return xxx_messageInfo_WorldToGamePacket.Size(m)
}
func (m *WorldToGamePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldToGamePacket.DiscardUnknown(m)
}

var xxx_messageInfo_WorldToGamePacket proto.InternalMessageInfo

func (m *WorldToGamePacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *WorldToGamePacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *WorldToGamePacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type LoginToWorldPacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginToWorldPacket) Reset()         { *m = LoginToWorldPacket{} }
func (m *LoginToWorldPacket) String() string { return proto.CompactTextString(m) }
func (*LoginToWorldPacket) ProtoMessage()    {}
func (*LoginToWorldPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{17}
}

func (m *LoginToWorldPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginToWorldPacket.Unmarshal(m, b)
}
func (m *LoginToWorldPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginToWorldPacket.Marshal(b, m, deterministic)
}
func (m *LoginToWorldPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginToWorldPacket.Merge(m, src)
}
func (m *LoginToWorldPacket) XXX_Size() int {
	return xxx_messageInfo_LoginToWorldPacket.Size(m)
}
func (m *LoginToWorldPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginToWorldPacket.DiscardUnknown(m)
}

var xxx_messageInfo_LoginToWorldPacket proto.InternalMessageInfo

func (m *LoginToWorldPacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *LoginToWorldPacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *LoginToWorldPacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type WorldToLoginPacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldToLoginPacket) Reset()         { *m = WorldToLoginPacket{} }
func (m *WorldToLoginPacket) String() string { return proto.CompactTextString(m) }
func (*WorldToLoginPacket) ProtoMessage()    {}
func (*WorldToLoginPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{18}
}

func (m *WorldToLoginPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldToLoginPacket.Unmarshal(m, b)
}
func (m *WorldToLoginPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldToLoginPacket.Marshal(b, m, deterministic)
}
func (m *WorldToLoginPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldToLoginPacket.Merge(m, src)
}
func (m *WorldToLoginPacket) XXX_Size() int {
	return xxx_messageInfo_WorldToLoginPacket.Size(m)
}
func (m *WorldToLoginPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldToLoginPacket.DiscardUnknown(m)
}

var xxx_messageInfo_WorldToLoginPacket proto.InternalMessageInfo

func (m *WorldToLoginPacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *WorldToLoginPacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *WorldToLoginPacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type WorldToDBPacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldToDBPacket) Reset()         { *m = WorldToDBPacket{} }
func (m *WorldToDBPacket) String() string { return proto.CompactTextString(m) }
func (*WorldToDBPacket) ProtoMessage()    {}
func (*WorldToDBPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{19}
}

func (m *WorldToDBPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldToDBPacket.Unmarshal(m, b)
}
func (m *WorldToDBPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldToDBPacket.Marshal(b, m, deterministic)
}
func (m *WorldToDBPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldToDBPacket.Merge(m, src)
}
func (m *WorldToDBPacket) XXX_Size() int {
	return xxx_messageInfo_WorldToDBPacket.Size(m)
}
func (m *WorldToDBPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldToDBPacket.DiscardUnknown(m)
}

var xxx_messageInfo_WorldToDBPacket proto.InternalMessageInfo

func (m *WorldToDBPacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *WorldToDBPacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *WorldToDBPacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type DBToWorldPacket struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgBody              []byte   `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBToWorldPacket) Reset()         { *m = DBToWorldPacket{} }
func (m *DBToWorldPacket) String() string { return proto.CompactTextString(m) }
func (*DBToWorldPacket) ProtoMessage()    {}
func (*DBToWorldPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{20}
}

func (m *DBToWorldPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBToWorldPacket.Unmarshal(m, b)
}
func (m *DBToWorldPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBToWorldPacket.Marshal(b, m, deterministic)
}
func (m *DBToWorldPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBToWorldPacket.Merge(m, src)
}
func (m *DBToWorldPacket) XXX_Size() int {
	return xxx_messageInfo_DBToWorldPacket.Size(m)
}
func (m *DBToWorldPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_DBToWorldPacket.DiscardUnknown(m)
}

var xxx_messageInfo_DBToWorldPacket proto.InternalMessageInfo

func (m *DBToWorldPacket) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *DBToWorldPacket) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *DBToWorldPacket) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

func init() {
	proto.RegisterEnum("ServerState", ServerState_name, ServerState_value)
	proto.RegisterEnum("ServerNodeMsgID", ServerNodeMsgID_name, ServerNodeMsgID_value)
	proto.RegisterType((*ServerReport)(nil), "ServerReport")
	proto.RegisterType((*ServerReportList)(nil), "ServerReportList")
	proto.RegisterType((*ServerHeartBeat)(nil), "ServerHeartBeat")
	proto.RegisterType((*NodeToMasterPacket)(nil), "NodeToMasterPacket")
	proto.RegisterType((*MasterToNodePacket)(nil), "MasterToNodePacket")
	proto.RegisterType((*GateToLoginPacket)(nil), "GateToLoginPacket")
	proto.RegisterType((*LoginToGatePacket)(nil), "LoginToGatePacket")
	proto.RegisterType((*GateToGamePacket)(nil), "GateToGamePacket")
	proto.RegisterType((*GameToGatePacket)(nil), "GameToGatePacket")
	proto.RegisterType((*GateToChatPacket)(nil), "GateToChatPacket")
	proto.RegisterType((*ChatToGatePacket)(nil), "ChatToGatePacket")
	proto.RegisterType((*WorldToGatePacket)(nil), "WorldToGatePacket")
	proto.RegisterType((*GateToWorldPacket)(nil), "GateToWorldPacket")
	proto.RegisterType((*GameToChatPacket)(nil), "GameToChatPacket")
	proto.RegisterType((*ChatToGamePacket)(nil), "ChatToGamePacket")
	proto.RegisterType((*GameToWorldPacket)(nil), "GameToWorldPacket")
	proto.RegisterType((*WorldToGamePacket)(nil), "WorldToGamePacket")
	proto.RegisterType((*LoginToWorldPacket)(nil), "LoginToWorldPacket")
	proto.RegisterType((*WorldToLoginPacket)(nil), "WorldToLoginPacket")
	proto.RegisterType((*WorldToDBPacket)(nil), "WorldToDBPacket")
	proto.RegisterType((*DBToWorldPacket)(nil), "DBToWorldPacket")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdb, 0xae, 0xdb, 0x44,
	0x14, 0x6d, 0xce, 0x35, 0xd9, 0x49, 0xdb, 0x39, 0x43, 0x39, 0xb8, 0x2a, 0x88, 0x10, 0x1e, 0x88,
	0x2a, 0x14, 0xa4, 0xf2, 0x05, 0x76, 0xec, 0xe4, 0x58, 0xb2, 0xc7, 0x91, 0xed, 0x52, 0xf5, 0xc9,
	0x38, 0xf1, 0x34, 0x44, 0xc4, 0x9e, 0xc8, 0x76, 0x50, 0xf3, 0x19, 0xdc, 0xa1, 0xdc, 0xf9, 0x15,
	0x04, 0x9f, 0xc1, 0xb7, 0xa0, 0xb9, 0x84, 0xe3, 0xba, 0x51, 0xdf, 0x7c, 0xde, 0x32, 0x7b, 0xed,
	0xb5, 0xd6, 0xec, 0x35, 0x23, 0x4f, 0x00, 0x32, 0x96, 0xd0, 0xd1, 0x26, 0x67, 0x25, 0x1b, 0xbc,
	0x38, 0x82, 0x5e, 0x40, 0xf3, 0x2f, 0x68, 0xee, 0xd3, 0x0d, 0xcb, 0x4b, 0xfc, 0x00, 0x3a, 0x85,
	0x58, 0x47, 0xab, 0x44, 0x6b, 0xf5, 0x5b, 0xc3, 0x53, 0xbf, 0x2d, 0x0b, 0x76, 0x82, 0xdf, 0x85,
	0xae, 0x02, 0xb3, 0x38, 0xa5, 0xda, 0x51, 0xbf, 0x35, 0xec, 0xf9, 0x20, 0x4b, 0x24, 0x4e, 0x69,
	0x95, 0xbd, 0xd1, 0x8e, 0x05, 0xbc, 0x67, 0x6f, 0x2a, 0x6c, 0xee, 0xa4, 0x9d, 0x08, 0x71, 0xc5,
	0x9e, 0x71, 0xef, 0x77, 0x00, 0xd2, 0xf8, 0x79, 0xc4, 0xb2, 0xf5, 0x2a, 0xa3, 0xda, 0xa9, 0xc0,
	0x3b, 0x69, 0xfc, 0xdc, 0x13, 0x05, 0x0e, 0x2f, 0xb6, 0xf9, 0x1e, 0x3e, 0x93, 0xf0, 0x62, 0x9b,
	0x2b, 0xf8, 0x23, 0xe8, 0x29, 0xf9, 0xa2, 0x8c, 0x4b, 0xaa, 0x9d, 0xf7, 0x5b, 0xc3, 0x3b, 0x8f,
	0x7a, 0x23, 0x39, 0x5e, 0xc0, 0x6b, 0xbe, 0xda, 0x80, 0x58, 0x54, 0xf6, 0x53, 0xee, 0x36, 0x54,
	0x6b, 0x57, 0xf7, 0x13, 0xee, 0x36, 0x74, 0x60, 0x00, 0xaa, 0x66, 0xe3, 0xac, 0x8a, 0x12, 0x8f,
	0xfe, 0x27, 0xad, 0xb2, 0x67, 0x4c, 0x6b, 0xf5, 0x8f, 0x87, 0xdd, 0x47, 0xb7, 0x47, 0xd5, 0xbe,
	0xbd, 0x86, 0x9d, 0x3d, 0x63, 0x83, 0x0f, 0xe0, 0xae, 0xc4, 0xae, 0x68, 0x9c, 0x97, 0x06, 0x8d,
	0x4b, 0x7c, 0x0f, 0x4e, 0x17, 0x6c, 0x9b, 0x95, 0x2a, 0x5e, 0xb9, 0x18, 0x98, 0x80, 0x09, 0x4b,
	0x68, 0xc8, 0xdc, 0xb8, 0x28, 0x69, 0x3e, 0x8b, 0x17, 0x9f, 0xd3, 0x03, 0x76, 0xad, 0xd7, 0xdb,
	0x7d, 0x08, 0x58, 0xf2, 0x43, 0xc6, 0xd5, 0x94, 0xca, 0x25, 0x9c, 0xe5, 0xb4, 0xd8, 0xae, 0xf7,
	0x96, 0x6a, 0x35, 0x98, 0xc3, 0xc5, 0x34, 0x2e, 0x69, 0xc8, 0x1c, 0xb6, 0x5c, 0x65, 0xaa, 0xf9,
	0x01, 0x74, 0x36, 0xeb, 0x78, 0x77, 0x7d, 0x03, 0x4e, 0xfc, 0xb6, 0x2c, 0xd8, 0x09, 0x7e, 0x13,
	0xce, 0xd2, 0x62, 0xc9, 0x91, 0x23, 0xb9, 0xf9, 0xb4, 0x58, 0xda, 0x09, 0xbe, 0x0f, 0x6d, 0x5e,
	0x9e, 0xb3, 0x64, 0xa7, 0x8e, 0xfd, 0x3c, 0x2d, 0x96, 0x06, 0x4b, 0x76, 0xdc, 0x43, 0xa8, 0x87,
	0x8c, 0x5b, 0x35, 0xe3, 0x11, 0x03, 0x92, 0x73, 0x4c, 0xe3, 0xb4, 0x49, 0x8b, 0x94, 0xde, 0xc8,
	0x14, 0xe3, 0xcf, 0xe2, 0xb2, 0x31, 0x0b, 0x2e, 0xde, 0xe4, 0x14, 0x73, 0xb8, 0x78, 0xc2, 0xf2,
	0x75, 0xd2, 0xb0, 0x87, 0x4c, 0x4a, 0x38, 0x35, 0x7c, 0xe0, 0x37, 0x72, 0x1a, 0x69, 0x93, 0x49,
	0xa5, 0xcd, 0x26, 0x55, 0x3d, 0xf1, 0xa6, 0xe6, 0x58, 0x00, 0x56, 0x5f, 0x91, 0x06, 0x07, 0x59,
	0x00, 0x56, 0x83, 0x34, 0xf8, 0x3d, 0xfc, 0x14, 0xee, 0x2a, 0x13, 0xd3, 0x68, 0xcc, 0xc1, 0x34,
	0x9a, 0x0c, 0xea, 0x61, 0x08, 0xdd, 0xca, 0xab, 0x8a, 0x7b, 0xd0, 0x0e, 0x82, 0x68, 0xec, 0xeb,
	0xc1, 0x15, 0xba, 0x85, 0x6f, 0x43, 0x27, 0x08, 0x22, 0xe2, 0xf9, 0xae, 0xee, 0xa0, 0x16, 0xee,
	0xc2, 0x79, 0x10, 0x44, 0xc6, 0xe3, 0xe0, 0x29, 0x3a, 0x52, 0x8b, 0x89, 0xed, 0x5b, 0xe8, 0x18,
	0xdf, 0x01, 0x08, 0x82, 0xc8, 0xd5, 0x6d, 0x12, 0x5a, 0x04, 0x9d, 0x3c, 0xfc, 0xf7, 0x64, 0xff,
	0x56, 0xf2, 0xa7, 0xcb, 0x2d, 0x96, 0xb6, 0x89, 0x2f, 0x01, 0x07, 0x96, 0xff, 0x89, 0xe5, 0x47,
	0xc4, 0x33, 0xad, 0xc8, 0x0d, 0xa6, 0x91, 0x6d, 0xa2, 0x5b, 0x58, 0x83, 0x37, 0xa6, 0x7a, 0x68,
	0x45, 0xbe, 0xf7, 0x38, 0xb4, 0xa2, 0xd0, 0x8b, 0x1c, 0x6f, 0x6a, 0x13, 0xf4, 0x25, 0xe1, 0x88,
	0xf8, 0x7d, 0x0d, 0xf1, 0x46, 0xf4, 0x15, 0xc1, 0x6f, 0x01, 0x7e, 0x99, 0x33, 0xd5, 0x5d, 0x0b,
	0x7d, 0xad, 0x00, 0xd7, 0xaa, 0x31, 0xbe, 0x39, 0xc0, 0x18, 0x5f, 0xe9, 0x21, 0xfa, 0x56, 0x00,
	0xfc, 0x67, 0x8d, 0xf1, 0x9d, 0x70, 0x7f, 0xe2, 0xf9, 0x8e, 0x59, 0x43, 0xbe, 0x27, 0xaf, 0xee,
	0x58, 0xf4, 0xa1, 0x1f, 0x0e, 0xd8, 0x0b, 0x97, 0x1f, 0x0f, 0xba, 0xb8, 0x16, 0x7a, 0xa1, 0xb4,
	0xdc, 0x57, 0xb4, 0x7e, 0x3a, 0xec, 0xef, 0x5a, 0xe8, 0x67, 0x82, 0xef, 0xc3, 0xbd, 0x5a, 0x2e,
	0x92, 0xf4, 0x8b, 0x80, 0x6a, 0x24, 0x99, 0xe6, 0xaf, 0x04, 0x5f, 0xc2, 0x45, 0x0d, 0x32, 0x0d,
	0xf4, 0x9b, 0xa8, 0x9b, 0x46, 0x5d, 0xea, 0x77, 0x21, 0x35, 0x73, 0xf4, 0xa7, 0x96, 0x5f, 0x0b,
	0xe0, 0x0f, 0x01, 0xbd, 0x1c, 0x80, 0x6c, 0x44, 0x7f, 0x5e, 0xcf, 0xa3, 0xa8, 0xde, 0x64, 0xe2,
	0xd8, 0xc4, 0x42, 0x7f, 0x11, 0xfc, 0x1e, 0xbc, 0xed, 0x5b, 0x33, 0xcf, 0x0f, 0xa3, 0xb1, 0x63,
	0x5b, 0x24, 0x8c, 0x6c, 0x32, 0xf1, 0x38, 0x59, 0xde, 0x0a, 0xf4, 0x0f, 0xc1, 0x43, 0x78, 0xdf,
	0xd5, 0x83, 0x90, 0x5b, 0xca, 0x4e, 0x75, 0x61, 0x6a, 0x9d, 0x7f, 0x93, 0xf9, 0x99, 0xf8, 0xcf,
	0xfb, 0xf1, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x81, 0x98, 0xc0, 0x01, 0x0b, 0x00, 0x00,
}
